/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package com.jedykerby.reserveandorder;

import javax.swing.JOptionPane;

import dbms.DatabaseManager;

/**
 *
 * @author YTAC
 */
public class SignUpDialog extends java.awt.Dialog {

    /**
     * Creates new form SignUpDialog
     */

    public SignUpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputPass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        reInputPass = new javax.swing.JTextField();
        register = new javax.swing.JToggleButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 24)); // NOI18N
        jLabel1.setText("Sign Up");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Username:");

        inputUserName.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        inputUserName.setText("Username");
        inputUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputUserNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputUserNameFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel3.setText("Password:");

        inputPass.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        inputPass.setText("Password");
        inputPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputPassFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel4.setText("Re-enter Password");

        reInputPass.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        reInputPass.setText("Re-enter Password");
        reInputPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reInputPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reInputPassFocusLost(evt);
            }
        });
        reInputPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reInputPassActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(255, 153, 102));
        register.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(register)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(inputPass)
                        .addComponent(reInputPass)
                        .addComponent(inputUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reInputPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(register)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        
        SignInDialog dialog = new SignInDialog(null, false);
        dialog.setVisible(true);
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        
        String username = inputUserName.getText();
        String password = inputPass.getText();
        String rePassword = reInputPass.getText();

        if (!password.equals(rePassword)) {

            JOptionPane.showMessageDialog(
                this, 
                "Password does not match", 
                "Error", 
                JOptionPane.INFORMATION_MESSAGE);

            return;
        }

        if (DatabaseManager.checkUser(username)) {

            JOptionPane.showMessageDialog(
                this, 
                "User already Existing", 
                "Error", 
                JOptionPane.INFORMATION_MESSAGE);

            return;
        }
        
        DatabaseManager.addCustomer(username, rePassword);

        SignInDialog dialog = new SignInDialog(null, false);
        dialog.setVisible(true);
        
        setVisible(false);
        dispose();

    }//GEN-LAST:event_registerActionPerformed

    private void reInputPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reInputPassActionPerformed
        
        if (reInputPass.getText().equals("Re-enter Password")) {
            reInputPass.setText("");
        }

    }//GEN-LAST:event_reInputPassActionPerformed

    private void inputUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUserNameFocusGained
            
        if (inputUserName.getText().equals("Username")) {
            inputUserName.setText("");
        }
    }//GEN-LAST:event_inputUserNameFocusGained

    private void inputUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputUserNameFocusLost
            
        if (inputUserName.getText().isBlank()) {
            inputUserName.setText("Username");
        }
    }//GEN-LAST:event_inputUserNameFocusLost

    private void inputPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPassFocusGained
        
        if (inputPass.getText().equals("Password")) {
            inputPass.setText("");
        }
    }//GEN-LAST:event_inputPassFocusGained

    private void inputPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputPassFocusLost
        
        if (inputPass.getText().equals("")) {
            inputPass.setText("Password");
        }
    }//GEN-LAST:event_inputPassFocusLost

    private void reInputPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reInputPassFocusGained
        
        if (reInputPass.getText().equals("Re-enter Password")) {
            reInputPass.setText("");
        }
    }//GEN-LAST:event_reInputPassFocusGained

    private void reInputPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reInputPassFocusLost
        
        if (reInputPass.getText().isBlank()) {
            reInputPass.setText("Re-enter Password");
        }
    }//GEN-LAST:event_reInputPassFocusLost

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputPass;
    private javax.swing.JTextField inputUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField reInputPass;
    private javax.swing.JToggleButton register;
    // End of variables declaration//GEN-END:variables
}
